### ISSUE TITLE
Index PULFA EADs in Staging

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/plantain#12]

**Comment by jrgriffiniii** [comment]
This should include running the ArcLight generator in order to integrate the new Traject configuration, but the functionality introduced in https://github.com/pulibrary/plantain/pull/1/ should still be ported where appropriate.

**Comment by jrgriffiniii** [comment]
This is going to require that the PULFA EADs be checked out by SVN in https://github.com/pulibrary/princeton_ansible/blob/master/playbooks/plantain_staging.yml

**Comment by jrgriffiniii** [comment]
Blocked by https://github.com/pulibrary/princeton_ansible/pull/933

**Comment by hackmastera** [comment]
The indexing is complete but there are a couple of loose ends still on the ansible side, which @jrgriffiniii is working on. I'll re-assign the ticket.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/princeton_ansible/pull/991/checks?check_run_id=293466533 is failing with an error which I did not encounter when provisioning from my local development environment - I will look to remedy this and continue with https://github.com/pulibrary/princeton_ansible/pull/991

**Comment by hackmastera** [comment]
Just a note that it took about 5 hours with 3 workers (all on the same box as solr and the web app).
