### ISSUE TITLE
authenticate with cas for sidekiq admin

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/plantain#55]

**Comment by tampakis** [comment]
Apps that use cas, also have an omniauth callbacks controller.
Pulmap: https://github.com/pulibrary/pulmap/blob/master/app/controllers/users/omniauth_callbacks_controller.rb
Figgy: https://github.com/pulibrary/figgy/commit/83d1a2433be882f71047ad7ab13b942d39b92ea9#diff-a4275c3adf0e6810f2de8c6b215f6645
